# Based on https://github.com/mhart/alpine-node/blob/12.16.1/slim.dockerfile

FROM node:12-alpine

FROM jcxldn/jenkins-containers:base

COPY --from=0 /usr/bin/node /usr/bin/node
COPY --from=0 /usr/bin/npm /usr/bin/npm

RUN apk upgrade --no-cache -U && \
  apk add --no-cache binutils libstdc++ && \
  strip /usr/bin/node && \
  strip /usr/bin/npm && \
  apk del binutils