name: builder

on:
  push:
    branches: master

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to Docker Hub
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx (base image)
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=true" \
            -f alpine/base.Dockerfile -t jcxldn/jenkins-containers:base .
      -
        name: Run Buildx (node12 image)
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=true" \
            -f alpine/node12.Dockerfile -t jcxldn/jenkins-containers:node12 .
      -
        name: Run Buildx (jdk11-gradle image)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64,linux/s390x \
            --output "type=image,push=true" \
            -f ubuntu/jdk11-gradle.Dockerfile -t jcxldn/jenkins-containers:jdk11-gradle-ubuntu .
